---
title: "Spotify_data"
author: "Ali Rishty"
date: "4/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
Data Extraction and Cleaning

```{r Spotify Data Extraction to CSV}
library('spotifyr')
library('ggplot2')

Sys.setenv(SPOTIFY_CLIENT_ID = '0485df77ffce426caf91a3f6c52a1d30')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '4f5774c394e6407588489ae09a25353b')


playlist_username <- 'spotify'
playlist_uris <- c('37i9dQZF1DX0uqkwkR49kK', '37i9dQZF1DWWEJlAGA9gs0', '37i9dQZF1DWWGFQLoP9qlv', '37i9dQZF1DX9GRpeH4CL0S', '37i9dQZF1DWT5MrZnPU1zD', '37i9dQZF1DXbYM3nMM0oPk', '37i9dQZF1DWTkxQvqMy4WW', '37i9dQZF1DX4SBhb3fqCJd', '37i9dQZF1DWVcbzTgVpNRm', '37i9dQZF1DX6z20IXmBjWI', '37i9dQZF1DXbITWG1ZJKYt', '37i9dQZF1DWULEW2RfoSCi', '37i9dQZF1DXdfOcg1fm0VG', '37i9dQZF1DWWOaP4H0w5b0', '37i9dQZF1DXbSbnqxMTGx9', '37i9dQZF1DXd9rSDyQguIk', '37i9dQZF1DXa9wYJr1oMFq', '37i9dQZF1DX1MUPbVKMgJE', '37i9dQZF1DX7WJ4yDmRK8R', '37i9dQZF1DX0BcQWzuB7ZO')

playlist_audio_features <- get_playlist_audio_features(playlist_username, playlist_uris)

head(playlist_audio_features)
names(playlist_audio_features)


#Extract first artist's name from each song's list of artists/profile
artist_vec = c()
for (i in 1:nrow(playlist_audio_features)){
  
  if(is.null(playlist_audio_features$track.artists[[i]]$name[1])){
    print(i)
  }
  artist_vec = c(artist_vec, playlist_audio_features$track.artists[[i]]$name[1])
}


song_df = playlist_audio_features %>% mutate(artist = artist_vec) %>%
  select(song = track.name, artist, genre=playlist_name, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, time_signature, popularity = track.popularity) %>% mutate(popularity = popularity/100, time_signature =  time_signature-3, loudness = (loudness+60)/60, key = key/100, tempo = tempo/1000)


song_df <- song_df %>% mutate(genre= gsub("Prog Rock Monsters", "Progressive Rock", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Classical Essentials", "Classical", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Legendary", "Classic Rock", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Essential Alternative", "Alternative Rock", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Hip Hop Controller", "Hip-Hop", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Mega Hit Mix", "Pop", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Chillin' on a Dirt Road", "Country", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Are & Be", "R&B", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Latin Party Anthems", "Latin", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Infinite Acoustic", "Folk", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Jazz Classics", "Jazz", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Soul Classics 1970–1975", "Soul", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Metal Essentials", "Metal", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Reggae Classics", "Reggae", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Blues Classics", "Blues", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Pop Punk Powerhouses", "Punk", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Disco Forever", "Disco/Funk", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("The Essential Ska", "Ska", genre, fixed=TRUE))
song_df <- song_df %>% mutate(genre= gsub("Dance Hits", "EDM", genre, fixed=TRUE))


write.csv(song_df,"Spotify_data.csv", row.names = FALSE)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
song_df %>% 
      ggplot(., aes(x=valence, y=energy)) + geom_point(aes(color = genre, size=6)) + ggtitle("Explore Track Metrics by Genre")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
